[package]
name = "blog_os"
version = "0.1.0"
authors = ["tommy <kazu9su@gmail.com>"]

[dependencies]
bootloader_precompiled = "0.2.0"

[package.metadata.bootimage]
default-target = "x86_64-blog_os.json"
